# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lane Larochelle
email: lanelarochelle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lane Larochelle exploring AWS as well as jekyll in web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lanelarochelle.com" # the base hostname & protocol for your site
github_username:  lanelarochelle

# Build settings
markdown: kramdown
